---
title: "Lecture 11 (Data Wrangling II)"
author: "CJ Snyder"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
```

# Loading data from the WEB...NON-SELECTOR-GADGET
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)

drug_use_xml

```

# Table-tag (if you see tables on a website)
```{r}
drug_use_xml %>% 
  html_nodes(css = "table")

# Pulling out the 15 tables included on the webpage.

table_marj = 
  (drug_use_xml %>%  html_nodes(css="table")) %>% 
  .[[1]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()

table_marj
```
The double square brackets indicates the # table you want to extract from the "tables" from the website.


## Practice Problem
```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
cost_of_living_xml = read_html(url)

cost_of_living_xml

cost_of_living_xml %>% 
    html_nodes(css="table")

cost_of_living = 
  (cost_of_living_xml %>%  html_nodes(css="table")) %>% 
  .[[1]] %>% 
  html_table(header=TRUE)


# ALTERNATIVE WAY!!
nyc_cost = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>%
  html_nodes(css = "table") %>%
  .[[1]] %>%
  html_table(header = TRUE)
```


# CSS SELECTORS
```{r}
hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")

title_vec = 
  hpsaga_html %>%
  html_nodes(".lister-item-header a") %>%
  html_text()

gross_rev_vec = 
  hpsaga_html %>%
  html_nodes(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = 
  hpsaga_html %>%
  html_nodes(".runtime") %>%
  html_text()

hpsaga_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

## Practice Problem 
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

# DOESN'T WORK!!!!!!!!!!
```


# Using an API
```{r}
# Easy way to download the data
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")

# Using a JSON file with API 
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```













